import fs from 'node:fs/promises';
import path from 'node:path';
import open from 'open';
import { env } from '../config/env.js';
import { emailService } from './email.service.js';
import { localAutomationService } from './localAutomation.service.js';

const sanitizeFilename = (value) => value.replace(/[^a-z0-9-_]/gi, '-').slice(0, 50);

export const taskExecutorService = {
  execute: async ({ action, args = {}, command }) => {
    const progress = ['Parsing instruction', `Selected action: ${action}`];

    switch (action) {
      case 'open_whatsapp': {
        progress.push('Trying to open installed WhatsApp');
        const execution = await localAutomationService.openKnownApp({ appName: 'whatsapp' });
        return { ...execution, progress };
      }

      case 'open_word': {
        progress.push('Trying to open Microsoft Word');
        const execution = await localAutomationService.openKnownApp({ appName: 'word' });
        return { ...execution, progress };
      }

      case 'open_chrome': {
        progress.push('Trying to open Google Chrome');
        const execution = await localAutomationService.openKnownApp({ appName: 'chrome' });
        return { ...execution, progress };
      }

      case 'open_folder_downloads': {
        progress.push('Opening Downloads folder');
        const execution = await localAutomationService.openDownloadsFolder();
        return { ...execution, progress };
      }

      case 'play_music': {
        progress.push('Trying to open local music player');
        const execution = await localAutomationService.playMusic({ songPath: args.songPath });
        return { ...execution, progress };
      }

      case 'open_app': {
        progress.push(`Trying to open installed app: ${args.appName}`);
        const execution = await localAutomationService.openKnownApp({ appName: args.appName ?? '' });
        return { ...execution, progress };
      }

      case 'compose_email': {
        const body = args.body ?? command;
        const subject = args.subject ?? 'Draft from AI Assistant';
        const mailToUrl = `mailto:${encodeURIComponent(args.to ?? '')}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
        progress.push('Opening default mail client with draft content');
        await open(mailToUrl);

        return {
          status: 'completed',
          progress,
          result: { message: 'Mail draft opened in your default mail client.' },
        };
      }

      case 'create_document': {
        const title = sanitizeFilename(args.title ?? 'document');
        const documentPath = path.join(env.agentArtifactsDir, `${title}-${Date.now()}.txt`);
        progress.push('Creating local document artifact');
        await fs.mkdir(env.agentArtifactsDir, { recursive: true });
        await fs.writeFile(
          documentPath,
          `Generated by AI Assistant\n\nCommand: ${command}\n\nCreated at: ${new Date().toISOString()}`,
          'utf8',
        );

        return {
          status: 'completed',
          progress,
          result: { message: 'Document created successfully.', path: documentPath },
        };
      }

      case 'send_email': {
        if (!args.to) {
          return {
            status: 'blocked',
            progress,
            result: { message: 'Missing recipient email. Include "to" in the command.' },
          };
        }

        progress.push('Sending email through configured SMTP provider');
        await emailService.sendEmail({
          to: args.to,
          subject: args.subject ?? 'Message from AI Assistant',
          body: args.body ?? 'Sent via task runner.',
        });

        return {
          status: 'completed',
          progress,
          result: { message: `Email sent to ${args.to}.` },
        };
      }

      case 'chat_only':
      default:
        return {
          status: 'blocked',
          progress,
          result: {
            message:
              'This instruction does not map to an executable local task. It was handled as a normal chat instruction.',
          },
        };
    }
  },
};
