import fs from 'node:fs/promises';
import path from 'node:path';
import open from 'open';
import { env } from '../config/env.js';
import { emailService } from './email.service.js';

const sanitizeFilename = (value) => value.replace(/[^a-z0-9-_]/gi, '-').slice(0, 50);

export const taskExecutorService = {
  execute: async ({ action, args = {}, command }) => {
    const progress = ['Parsing instruction', `Selected action: ${action}`];

    switch (action) {
      case 'open_whatsapp': {
        progress.push('Opening WhatsApp Web');
        await open('https://web.whatsapp.com');
        return {
          status: 'completed',
          progress,
          result: { message: 'WhatsApp Web opened in browser.' },
        };
      }

      case 'open_word': {
        progress.push('Trying to open Microsoft Word');
        try {
          await open.apps.open('winword');
          return {
            status: 'completed',
            progress,
            result: { message: 'Microsoft Word opened.' },
          };
        } catch (error) {
          return {
            status: 'failed',
            progress,
            result: {
              message:
                'Could not open Microsoft Word automatically. Ensure Office is installed on this machine.',
            },
          };
        }
      }

      case 'compose_email': {
        const body = args.body ?? command;
        const subject = args.subject ?? 'Draft from AI Assistant';
        const mailToUrl = `mailto:${encodeURIComponent(args.to ?? '')}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
        progress.push('Opening default mail client with draft content');
        await open(mailToUrl);

        return {
          status: 'completed',
          progress,
          result: { message: 'Mail draft opened in your default mail client.' },
        };
      }

      case 'create_document': {
        const title = sanitizeFilename(args.title ?? 'document');
        const documentPath = path.join(env.agentArtifactsDir, `${title}-${Date.now()}.txt`);
        progress.push('Creating local document artifact');
        await fs.mkdir(env.agentArtifactsDir, { recursive: true });
        await fs.writeFile(
          documentPath,
          `Generated by AI Assistant\n\nCommand: ${command}\n\nCreated at: ${new Date().toISOString()}`,
          'utf8',
        );

        return {
          status: 'completed',
          progress,
          result: { message: 'Document created successfully.', path: documentPath },
        };
      }

      case 'send_email': {
        if (!args.to) {
          return {
            status: 'blocked',
            progress,
            result: { message: 'Missing recipient email. Include "to" in the command.' },
          };
        }

        progress.push('Sending email through configured SMTP provider');
        await emailService.sendEmail({
          to: args.to,
          subject: args.subject ?? 'Message from AI Assistant',
          body: args.body ?? 'Sent via task runner.',
        });

        return {
          status: 'completed',
          progress,
          result: { message: `Email sent to ${args.to}.` },
        };
      }

      case 'chat_only':
      default:
        return {
          status: 'blocked',
          progress,
          result: {
            message:
              'This instruction does not map to an executable local task. It was handled as a normal chat instruction.',
          },
        };
    }
  },
};
